"""
Centralized configuration & path resolution.

All paths are resolved relative to the repository location (BASE_DIR), not the
current working directory, so every script can be run from any directory.
Output names, default inputs, and timeout/review-limit values do not change from
the contract locked in docs/baseline.md.

Author: Salman Abdurrahman
Date: 2025
"""

import os
import re

# Repository root: parent of this src/ folder
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------- folders
RAW_DIR = os.path.join(BASE_DIR, "data", "raw")
REVIEWS_JSON_DIR = os.path.join(BASE_DIR, "data", "reviews_json")
REVIEWS_JSON_V1_DIR = os.path.join(REVIEWS_JSON_DIR, "V1")
PROCESSED_DIR = os.path.join(BASE_DIR, "data", "processed")

# ---------------------------------------------------------------- output files (frozen names)
PLACES_LIST_FILE = os.path.join(RAW_DIR, "karawang_places_list.csv")
TOURISM_FINAL_FILE = os.path.join(PROCESSED_DIR, "karawang_tourism_final.csv")
PLACE_IMAGES_FILE = os.path.join(PROCESSED_DIR, "karawang_place_images.csv")
TOURISM_FINAL_WITH_IMAGES_FILE = os.path.join(PROCESSED_DIR, "karawang_tourism_final_with_images.csv")
CONTENT_BASED_FILE = os.path.join(PROCESSED_DIR, "karawang_places_content_based.csv")

# ---------------------------------------------------------------- compatibility mapping
# gmaps_scraper names its output from the query slug (<query_slug>_places_list.csv),
# while pipeline consumers (reviews & image scraper) use the canonical name
# karawang_places_list.csv. This mapping bridges generated names to existing
# files. If SEARCH_QUERY changes, add a new slug here.
RAW_CSV_NAME_COMPATIBILITY = {
    "tempat_wisata_di_karawang_places_list.csv": "karawang_places_list.csv",
}


def resolve_raw_csv_name(generated_name):
    """
    Maps a generated raw CSV name to the canonical existing name.

    Args:
        generated_name (str): File name generated by gmaps_scraper.

    Returns:
        str: Canonical name if present in the mapping, otherwise the original
        generated name.
    """
    return RAW_CSV_NAME_COMPATIBILITY.get(generated_name, generated_name)


# ---------------------------------------------------------------- search query
SEARCH_QUERY = "Tempat Wisata di Karawang"

# ---------------------------------------------------------------- review limits
MAX_REVIEWS_PER_PLACE = 400      # Reviews scraper target per place (text only)
SCROLL_EXTRA_BUFFER = 100        # Extra cards to compensate for empty reviews
MAX_SAMPLE_REVIEWS_PER_PLACE = 150  # Processing sampling: review cap per place

# ---------------------------------------------------------------- timeout (ms) & delay (s)
PAGE_LOAD_TIMEOUT = 60000   # Page navigation
SHORT_SELECTOR_TIMEOUT = 10000  # Short selector wait (searchbox, feed, h1)
SELECTOR_TIMEOUT = 15000    # Main selector for reviews scraper
FALLBACK_TIMEOUT = 5000     # Fallback selector for reviews scraper
SCROLL_PAUSE_TIME = 2       # Pause between scrolls (places scraper)
MAX_SCROLL_ATTEMPTS = 50    # Scroll attempt cap (places scraper)
TAB_SWITCH_DELAY = 2        # Delay after switching tabs (reviews scraper)
SCROLL_DELAY = 1.5          # Pause between scrolls (reviews scraper)

# ---------------------------------------------------------------- placeholder image
PLACEHOLDER_IMAGE_URL = "https://via.placeholder.com/400x300?text=No+Image"

# ---------------------------------------------------------------- google maps selectors
# Frozen: selector strings must not change without separate tests and approval
# (docs/baseline.md). Grouped here so scraper scripts reference constants
# instead of inline selector strings.

# Places list scraper (gmaps_scraper.py)
SELECTOR_SEARCHBOX = 'input#searchboxinput'
SELECTOR_RESULTS_FEED = 'div[role="feed"]'
SELECTOR_PLACE_LINK = 'a.hfpxzc'
SELECTOR_END_OF_LIST = "text=You've reached the end of the list"

# Reviews scraper (gmaps_reviews_scraper.py)
SELECTOR_PLACE_NAME = '.DUwDvf.lfPIob'
SELECTOR_H1 = 'h1'
SELECTOR_RATING_CONTAINER = '.fontBodyMedium.dmRWX'
SELECTOR_RATING_VALUE = 'span[aria-hidden="true"]'
SELECTOR_REVIEWS_COUNT_LABEL = 'span[aria-label*="ulasan"], span[aria-label*="reviews"]'
SELECTOR_CATEGORY_BUTTON = 'button.DkEaL'
SELECTOR_ADDRESS = '.Io6YTe.fontBodyMedium.kR99db.fdkmkc'
SELECTOR_TAB = 'div.Gpq6kf.NlVald'
ABOUT_TAB_PATTERN = re.compile(r"Tentang|About")
REVIEWS_TAB_PATTERN = re.compile(r"Ulasan|Reviews")
SELECTOR_DESCRIPTION = 'span.HlvSq'
SELECTOR_ATTRIBUTES = 'ul.ZQ6we li.hpLkke'
SELECTOR_MAIN_PANEL = 'div[role="main"]'
SELECTOR_REVIEW_CARD = 'div[data-review-id]'
SELECTOR_SEE_MORE_BUTTON = 'button.w8nwRe.kyuRq'
SELECTOR_REVIEW_TEXT = '.wiI7pd'
SELECTOR_REVIEW_USER = '.d4r55.fontTitleMedium'
SELECTOR_REVIEW_STARS_CONTAINER = '.DU9Pgb'
SELECTOR_REVIEW_FILLED_STAR = 'span.hCCjke'
SELECTOR_REVIEW_TIME = '.rsqaWe'

# Image scraper (gmaps_image_scraper.py)
SELECTOR_PHOTO_BUTTON = 'button.aoRNLd.kn2E5e.NMjTrf.lvtCsd'
SELECTOR_PHOTO_DIV = 'div.Uf0tqf.ch8jbf'
SELECTOR_HERO_IMAGE = 'div[role="img"] img'

# ---------------------------------------------------------------- helpers
def ensure_dir(path):
    """
    Creates a directory (and parents) if it does not exist.

    Args:
        path (str): Directory path to ensure.
    """
    os.makedirs(path, exist_ok=True)


def require_file(path):
    """
    Validates that a required input file exists before processing starts.

    Args:
        path (str): Path to the input file.

    Returns:
        bool: True if the file exists, False otherwise.
    """
    return os.path.isfile(path)


def require_dir(path):
    """
    Validates that a required input directory exists before processing starts.

    Args:
        path (str): Path to the input directory.

    Returns:
        bool: True if the directory exists, False otherwise.
    """
    return os.path.isdir(path)
